[package]
name = "pandoculation"
version = "0.1.0"
edition = "2021"

[build-dependencies]
schemafy = "0.6.0"
schemafy_lib = "0.6.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
